[workspace]

members = [
    "api-public",
    "api-private",
    "bootstrap",
    "network",
    "consensus",
    "crypto",
    "logging",
    "massa-node",
    "models",
    "pool",
    "protocol",
    "massa-client",
    "storage",
    "time",
    "wallet",
]
