[workspace]

members = [
    "api",
    "bootstrap",
    "network",
    "consensus",
    "crypto",
    "logging",
    "massa-node",
    "models",
    "pool",
    "massa-client",
    "protocol-worker",
    "protocol-exports",
    "storage",
    "time",
    "wallet",
]
