[workspace]

members = [
	"api",
    "bootstrap",
    "communication",
    "consensus",
    "crypto",
    "jsonrpc-api",
    "jsonrpc-client",
    "jsonrpc-dto",
    "logging",
    "massa-client",
    "massa-node",
    "models",
    "pool",
    "storage",
    "time",
    "wallet"
]
