[workspace]

members = [
	"api",
    "api-dto",
    "api-public",
    "api-private",
    "api-eth",
    "bootstrap",
    "communication",
    "consensus",
    "crypto",
    "logging",
    "massa-client",
    "massa-node",
    "models",
    "pool",
    "rpc-client",
    "rpc-server",
    "storage",
    "time",
    "wallet",
]
