[package]
name = "massa-node"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.11", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec"] }
futures = { version = "0.3" }
log = { version = "0.4" }
serde = { version = "1.0", features = ["derive"] }
config = { version = "0.11" }
stderrlog = { version = "0.5" }
logging = { path = "../logging" }
communication = { path = "../communication" }
consensus = { path = "../consensus" }
time = { path = "../time" }
api = { path = "../api" }
storage = { path = "../storage" }
models = { path = "../models" }
bootstrap = { path = "../bootstrap" }
pool = { path = "../pool" }
serde_json = { version = "1.0" }

[dev-dependencies]
stderrlog = { version = "0.5" }
pretty_assertions = "0.7"
serial_test = "0.5"
