[package]
name = "storage"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
displaydoc = "0.2"
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
sled = "0.34"
thiserror = "1.0"
tokio = { version = "1.11", features = ["full"] }
# custom modules
crypto = { path = "../crypto" }
logging = { path = "../logging" }
models = { path = "../models" }
time = { path = "../time" }

[dev-dependencies]
pretty_assertions = "0.7"
tempfile = "3.2"
serial_test = "0.5"
stderrlog = "0.5"
