[package]
name = "time"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
displaydoc = "0.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.11", features = ["full"] }

[dev-dependencies]
pretty_assertions = "0.7"
serial_test = "0.5"
