[package]
name = "rpc-client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2"
interact_prompt = "0.3.6"
jsonrpc-core-client = { version = "18.0.0", features = ["http", "tls"] }
paw = "1.0"
structopt = { version = "0.3", features = [ "paw" ] }
tokio = { version = "1", features = ["full"] }
